# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2efea16a36320600aa672d4800775937"
name = "Inventory Management"
application_url = "https://inventory-mng-shopify.vercel.app"
embedded = true
handle = "inventory-mng-grace"
web_directories = ["."]

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_inventory,read_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://inventory-mng-shopify.vercel.app/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
